site_name: Navio docs
theme_dir: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/navio-docs

pages:
- Introduction : 'index.md'
- Hardware setup: 'navio+/ardupilot/hardware-setup.md'
- Raspberry Pi configuration: 'common/navio-ardupilot/configuring-raspberry-pi.md'
- ArduPilot:
  - 'ArduPilot installation and running' : 'common/navio-ardupilot/installation-and-running.md'
  - 'Ardupilot upgrade' : 'common/navio-ardupilot/ardupilot-upgrade.md'
  - 'Building ArduPilot from sources': 'common/navio-ardupilot/building-from-sources.md'
- ROS: 'common/navio-dev/ros.md'
- Navio for developers:
  - 'Video streaming': 'common/navio-ardupilot/video-streaming.md'
  - 'Wi-Fi Broadcast' : 'common/navio-dev/wbc.md'
  - 'Examples setup': 'common/navio-dev/navio-repository-cloning.md'
  - 'Barometer' : 'common/navio-dev/barometer.md'
  - 'ADC' : 'navio+/dev/adc.md'
  - 'PWM output' : 'navio+/dev/pwm-output.md'
  - 'RC input' : 'navio+/dev/rc-input.md'
  - '9DOF IMU' : 'common/navio-dev/imu-mpu9250_lsm9ds1.md'
  - 'AHRS' : 'common/navio-dev/ahrs.md'
  - 'GPS' : 'common/navio-dev/gps-ublox.md'
  - 'GPS via u-center' : 'common/navio-dev/gps-ublox-ucenter.md'
  - 'FRAM' : 'navio+/dev/fram.md'
  - 'RGB LED' : 'common/navio-dev/rgb-led.md'
  - 'Datasheets' : 'navio+/dev/datasheets.md'
- Changelogs: 'common/navio-dev/changelogs.md'
- Community projects:
  - 'Windows IoT': 'common/Community-projects/Windows-IoT.md'
